import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller, acf, pacf
import logging
import matplotlib.pyplot as plt

class FeatureEngineering:
    def __init__(self, agg_data, config):
        self.logger = logging.getLogger(self.__class__.__name__)
        self.agg_data = agg_data
        self.config = config

    def create_lag_features(self):
        self.logger.debug("Creating manually specified lag features.")
        try:
            for lag in self.config['data']['lag_features']:
                self.agg_data[f'lag_{lag}'] = self.agg_data[self.config['data']['target_column']].shift(lag)
            return self.agg_data
        except Exception as e:
            self.logger.error(f"Error creating lag features: {e}")
            raise

    def create_rolling_features(self):
        self.logger.debug("Creating manually specified rolling average features.")
        try:
            for window in self.config['data']['rolling_windows']:
                self.agg_data[f'rolling_mean_{window}'] = self.agg_data[self.config['data']['target_column']].rolling(window=window).mean()
            return self.agg_data
        except Exception as e:
            self.logger.error(f"Error creating rolling features: {e}")
            raise

    def determine_lags(self, target_column, max_lag=20):
        self.logger.info("Running ADF Test and determining significant lags using ACF and PACF.")

        # ADF Test for Stationarity
        result = adfuller(self.agg_data[target_column].dropna())
        self.logger.info(f'ADF Statistic: {result[0]}, p-value: {result[1]}')

        if result[1] > 0.05:
            self.logger.info("Series is non-stationary, consider differencing.")
            # Apply differencing if necessary
            self.agg_data[target_column] = self.agg_data[target_column].diff().dropna()

        # ACF and PACF
        lag_acf = acf(self.agg_data[target_column], nlags=max_lag)
        lag_pacf = pacf(self.agg_data[target_column], nlags=max_lag, method='ols')

        # Plot ACF and PACF
        plt.figure(figsize=(12, 8))
        plt.subplot(211)
        plt.plot(lag_acf)
        plt.axhline(y=0, linestyle='--', color='gray')
        plt.axhline(y=-1.96/np.sqrt(len(self.agg_data[target_column])), linestyle='--', color='gray')
        plt.axhline(y=1.96/np.sqrt(len(self.agg_data[target_column])), linestyle='--', color='gray')
        plt.title('Autocorrelation Function')

        plt.subplot(212)
        plt.plot(lag_pacf)
        plt.axhline(y=0, linestyle='--', color='gray')
        plt.axhline(y=-1.96/np.sqrt(len(self.agg_data[target_column])), linestyle='--', color='gray')
        plt.axhline(y=1.96/np.sqrt(len(self.agg_data[target_column])), linestyle='--', color='gray')
        plt.title('Partial Autocorrelation Function')
        plt.tight_layout()
        plt.show()

        # Identify significant lags from PACF
        significant_lags = np.where(lag_pacf > 1.96/np.sqrt(len(self.agg_data[target_column])))[0]
        self.logger.info(f'Significant lags from PACF: {significant_lags}')

        return significant_lags

    def dynamic_feature_engineering(self, target_column, max_lag=20):
        self.logger.info("Starting dynamic feature engineering.")
        significant_lags = self.determine_lags(target_column, max_lag)

        # Create lag features dynamically
        for lag in significant_lags:
            self.agg_data[f'dynamic_lag_{lag}'] = self.agg_data[target_column].shift(lag)

        # Example: Choose rolling windows based on seasonality or other insights from ACF
        seasonal_lag = 12  # Example: monthly seasonality for a yearly dataset
        self.agg_data[f'dynamic_rolling_mean_{seasonal_lag}'] = self.agg_data[target_column].rolling(window=seasonal_lag).mean()
        self.agg_data[f'dynamic_rolling_std_{seasonal_lag}'] = self.agg_data[target_column].rolling(window=seasonal_lag).std()

        # Drop NaN values generated by lag/rolling calculations
        self.agg_data.dropna(inplace=True)

        return self.agg_data

    def drop_na(self):
        self.logger.debug("Dropping NA values.")
        try:
            self.agg_data = self.agg_data.dropna()
            return self.agg_data
        except Exception as e:
            self.logger.error(f"Error dropping NA values: {e}")
            raise